version: "3.7"
services:
  web:
    image: nerevarishe/vista_portal:latest
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - vista_portal_db:/srv/www/vista_portal/sqlite_db/
    restart: always
volumes:
  vista_portal_db:
