version: "3.7"
services:
  web:
    image: vista/news_site:latest
    ports:
      - "5000:5000"
    volumes:
      - vista_portal:/srv/www/news_site/
    restart: always
volumes:
  - vista_portal:
