"""adding IP field to defectura table

Revision ID: 027388dce3d3
Revises: f946c2403e4b
Create Date: 2018-10-24 06:01:15.408860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027388dce3d3'
down_revision = 'f946c2403e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defectura_card', sa.Column('ip', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('defectura_card', 'ip')
    # ### end Alembic commands ###
