"""adding spravka models

Revision ID: 090039237459
Revises: 027388dce3d3
Create Date: 2018-10-24 09:21:17.677739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090039237459'
down_revision = '027388dce3d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drugstore_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ds_name', sa.String(), nullable=True),
    sa.Column('ds_adress', sa.String(), nullable=True),
    sa.Column('ds_worktime', sa.String(), nullable=True),
    sa.Column('ds_phone', sa.String(), nullable=True),
    sa.Column('ds_ip_phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drugstore_list_ds_name'), 'drugstore_list', ['ds_name'], unique=False)
    op.create_table('service_center_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brands', sa.String(), nullable=True),
    sa.Column('sc_adress', sa.String(), nullable=True),
    sa.Column('sc_phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_center_list')
    op.drop_index(op.f('ix_drugstore_list_ds_name'), table_name='drugstore_list')
    op.drop_table('drugstore_list')
    # ### end Alembic commands ###
