"""empty message

Revision ID: 1a7862d5bf98
Revises: 839ccb06b4f8
Create Date: 2018-08-20 10:09:57.936523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a7862d5bf98'
down_revision = '839ccb06b4f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expdate_table_exp_date', table_name='expdate_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_expdate_table_exp_date', 'expdate_table', ['exp_date'], unique=False)
    # ### end Alembic commands ###
