"""empty message

Revision ID: 483a13dac4ee
Revises: 1a7862d5bf98
Create Date: 2018-08-21 08:17:37.037486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483a13dac4ee'
down_revision = '1a7862d5bf98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_expdate_table_exp_date'), 'expdate_table', ['exp_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expdate_table_exp_date'), table_name='expdate_table')
    # ### end Alembic commands ###
