"""empty message

Revision ID: 5c3fddb9dae3
Revises: a591793c416c
Create Date: 2018-09-10 04:05:25.562028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c3fddb9dae3'
down_revision = 'a591793c416c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edinfo_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edinfo_post_timestamp'), 'edinfo_post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edinfo_post_timestamp'), table_name='edinfo_post')
    op.drop_table('edinfo_post')
    # ### end Alembic commands ###
