"""empty message

Revision ID: 839ccb06b4f8
Revises: e579ce8a6733
Create Date: 2018-08-18 15:31:58.470110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839ccb06b4f8'
down_revision = 'e579ce8a6733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expdate_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(), nullable=True),
    sa.Column('exp_date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expdate_table_exp_date'), 'expdate_table', ['exp_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expdate_table_exp_date'), table_name='expdate_table')
    op.drop_table('expdate_table')
    # ### end Alembic commands ###
