"""adding source field in news table

Revision ID: 89397475a201
Revises: e866b61a9b71
Create Date: 2019-02-07 21:30:23.806852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89397475a201'
down_revision = 'e866b61a9b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('source', sa.String(), nullable=True))
    op.create_index(op.f('ix_news_source'), 'news', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_source'), table_name='news')
    op.drop_column('news', 'source')
    # ### end Alembic commands ###
