"""Schedule and Shift tables

Revision ID: 97adb97f6aad
Revises: 2348bacbf852
Create Date: 2018-11-17 13:36:05.252821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97adb97f6aad'
down_revision = '2348bacbf852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('shift', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employee', 'shift', ['shift'], ['id'])
    op.add_column('schedule', sa.Column('year', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'year')
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_column('employee', 'shift')
    # ### end Alembic commands ###
