"""Defectura table

Revision ID: b044877d7380
Revises: 5c3fddb9dae3
Create Date: 2018-09-22 07:48:19.198616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b044877d7380'
down_revision = '5c3fddb9dae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defectura_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defectura_card_timestamp'), 'defectura_card', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_defectura_card_timestamp'), table_name='defectura_card')
    op.drop_table('defectura_card')
    # ### end Alembic commands ###
