"""empty message

Revision ID: bd459c5c0ec6
Revises: a95506b565fb
Create Date: 2018-08-08 14:14:33.472907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd459c5c0ec6'
down_revision = 'a95506b565fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_news_timestamp'), 'news', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_timestamp'), table_name='news')
    # ### end Alembic commands ###
