"""Defectura table adding date col

Revision ID: f946c2403e4b
Revises: b044877d7380
Create Date: 2018-09-22 08:33:38.188223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f946c2403e4b'
down_revision = 'b044877d7380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defectura_card', sa.Column('date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_defectura_card_date'), 'defectura_card', ['date'], unique=False)
    op.drop_index('ix_defectura_card_timestamp', table_name='defectura_card')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_defectura_card_timestamp', 'defectura_card', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_defectura_card_date'), table_name='defectura_card')
    op.drop_column('defectura_card', 'date')
    # ### end Alembic commands ###
